### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by jekuer**
Add my add-to-calendar button project (VanillaJS), which lets you easily render optimized buttons from simple JSON placeholders in any HTML. Despite other (not really up-to-date) popular packages, it considers new modern circumstances.

### CODE REVIEW

**Review by lptn — APPROVED** [review]
Approving, thanks @jekuer.

One note: can you please order these JD packages by a number of stars on GitHub? I think this option is not ideal, but it's also not fair to put a package with 3 stars at the top of this list.

**Comment by jekuer** [comment]
Thanks for the review. Will do so and give you an update soon.

**Comment by jekuer** [comment]
Hi @lptn ,
after going crazy on ProductHunt (https://www.producthunt.com/posts/add-to-calendar-button-generator), it should now match the requirements :).

**Comment by lptn** [comment]
@jekuer congrats, merging!

**Pull request merged**
